version: "3.2"
services:
     refapp-tomcat:
         build:
             context: ./tomcat
         container_name: refapp-tomcat
         ports:
             - "80:8080"
         networks:
             - network
         depends_on:
             - "refapp-db"
         volumes:
           - type: bind
             source: ./data/webapps
             target: /usr/local/tomcat/webapps
           - type: bind
             source: ./data/OpenMRS
             target: /usr/local/tomcat/.OpenMRS
         restart: unless-stopped

     refapp-db:
         build:
             context: ./mysql
         container_name: refapp-db
         ports:
             - "3320:3306"
         networks:
             - network
         volumes:
             - datadb:/var/lib/mysql
         restart: unless-stopped

networks:
  network:
    driver: bridge

volumes:
  datadb:
